# Generated by Django 2.2.5 on 2019-09-12 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0004_availablespec_interactedproduct'),
        ('user', '0003_agent_agentgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序优先级')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_delete', models.BooleanField(default=True, verbose_name='是否删除')),
                ('delete_time', models.DateTimeField(blank=True, default=0, null=True, verbose_name='删除时间')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('extends', models.TextField(blank=True, null=True, verbose_name='扩展数据(json格式存储)')),
                ('currency', models.CharField(default='', max_length=3, verbose_name='结算币种')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='成本价')),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='供货价')),
                ('has_tiered_pricing', models.BooleanField(default=False, verbose_name='是否设置阶梯价格')),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='零售价')),
                ('suggested_retail_price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='建议零售价')),
                ('is_general', models.BooleanField(default=True, verbose_name='是否为通用价格')),
                ('agent_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pricing_set', to='user.AgentGroup', verbose_name='所属分组')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pricing', to='product.Spec', verbose_name='所属规格')),
            ],
            options={
                'verbose_name': '定价',
                'verbose_name_plural': '定价',
                'db_table': 't_pricing',
                'ordering': ('-sort', '-add_time'),
            },
        ),
        migrations.CreateModel(
            name='TieredPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序优先级')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_delete', models.BooleanField(default=True, verbose_name='是否删除')),
                ('delete_time', models.DateTimeField(blank=True, default=0, null=True, verbose_name='删除时间')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('extends', models.TextField(blank=True, null=True, verbose_name='扩展数据(json格式存储)')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tiered_pricing', to='pricing.Pricing', verbose_name='隶属价格体系')),
            ],
            options={
                'verbose_name': '阶梯定价',
                'verbose_name_plural': '阶梯定价',
                'db_table': 't_tiered_pricing',
                'ordering': ('-sort', '-add_time'),
            },
        ),
        migrations.CreateModel(
            name='StepPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序优先级')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_delete', models.BooleanField(default=True, verbose_name='是否删除')),
                ('delete_time', models.DateTimeField(blank=True, default=0, null=True, verbose_name='删除时间')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('extends', models.TextField(blank=True, null=True, verbose_name='扩展数据(json格式存储)')),
                ('min_quantity', models.PositiveIntegerField(default=0, verbose_name='最小可购买数量')),
                ('max_quantity', models.PositiveIntegerField(default=0, verbose_name='最大可购买数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='价格')),
                ('tiered_pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_price', to='pricing.TieredPricing', verbose_name='所属阶梯价格')),
            ],
            options={
                'verbose_name': '阶梯价格',
                'verbose_name_plural': '阶梯价格',
                'db_table': 't_step_prices',
                'ordering': ('-sort', '-add_time'),
            },
        ),
    ]
