# Generated by Django 2.2.5 on 2019-09-17 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_auto_20190914_1407'),
        ('pricing', '0002_auto_20190914_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='express_fee_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pricing', to='logistics.ExpressFeeGroup', verbose_name='快递费模板'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='is_free_shipping',
            field=models.BooleanField(default=True, verbose_name='是否包邮'),
        ),
    ]
