# Generated by Django 2.2.5 on 2019-09-18 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_auto_20190917_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tieredpricing',
            old_name='price',
            new_name='pricing',
        ),
    ]
