# Generated by Django 2.2.5 on 2019-09-11 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序优先级')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_delete', models.BooleanField(default=True, verbose_name='是否删除')),
                ('delete_time', models.DateTimeField(blank=True, default=0, null=True, verbose_name='删除时间')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('extends', models.TextField(blank=True, null=True, verbose_name='扩展数据(json格式存储)')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('letter', models.CharField(blank=True, max_length=30, null=True, verbose_name='名称拼写')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('slogan', models.CharField(blank=True, max_length=80, null=True, verbose_name='标语')),
                ('bg_color', models.CharField(blank=True, max_length=30, null=True, verbose_name='背景色')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='是否首页推荐')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_brands', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
                'db_table': 't_brands',
                'ordering': ('-sort', '-add_time'),
            },
        ),
    ]
