# Generated by Django 2.2.5 on 2019-09-11 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序优先级')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_delete', models.BooleanField(default=True, verbose_name='是否删除')),
                ('delete_time', models.DateTimeField(blank=True, default=0, null=True, verbose_name='删除时间')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('extends', models.TextField(blank=True, null=True, verbose_name='扩展数据(json格式存储)')),
                ('name', models.CharField(default='', max_length=30, verbose_name='分类名称')),
                ('vice_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='分类副标题')),
                ('slogan', models.CharField(blank=True, max_length=100, null=True, verbose_name='分类标语')),
                ('bg_color', models.CharField(blank=True, max_length=10, null=True, verbose_name='分类背景色')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='是否首页推荐')),
                ('parent', models.ForeignKey(blank=True, db_column='pid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.Category', verbose_name='父级分类')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'db_table': 't_categories',
                'ordering': ('-sort', '-add_time'),
            },
        ),
    ]
