# Generated by Django 2.2.5 on 2019-09-12 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0002_region_shippinginfo_trackingrecord'),
        ('product', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序优先级')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_delete', models.BooleanField(default=True, verbose_name='是否删除')),
                ('delete_time', models.DateTimeField(blank=True, default=0, null=True, verbose_name='删除时间')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('extends', models.TextField(blank=True, null=True, verbose_name='扩展数据(json格式存储)')),
                ('name', models.CharField(max_length=80, verbose_name='产品名称')),
                ('item_no', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='货号')),
                ('brief', models.CharField(blank=True, max_length=160, null=True, verbose_name='产品简述')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='产品描述')),
                ('is_id_needed', models.BooleanField(default=False, verbose_name='是否需要ID')),
                ('access_count', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='点赞次数')),
                ('favorite_count', models.PositiveIntegerField(default=0, verbose_name='收藏次数')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='是否首页推荐')),
                ('brand', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.Brand', verbose_name='产品品牌')),
                ('category', models.ManyToManyField(related_name='products', to='product.Category', verbose_name='产品所属分类')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建该产品的用户')),
                ('place_delivery', models.ForeignKey(blank=True, db_column='delivery_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivery_products', to='logistics.Region', verbose_name='发货地')),
                ('place_origin', models.ForeignKey(blank=True, db_column='origin_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='origin_products', to='logistics.Region', verbose_name='产地')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 't_products',
                'ordering': ('-sort', '-add_time'),
            },
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序优先级')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_delete', models.BooleanField(default=True, verbose_name='是否删除')),
                ('delete_time', models.DateTimeField(blank=True, default=0, null=True, verbose_name='删除时间')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('extends', models.TextField(blank=True, null=True, verbose_name='扩展数据(json格式存储)')),
                ('name', models.CharField(max_length=30, verbose_name='规格名称')),
                ('value', models.CharField(max_length=30, verbose_name='规格值')),
                ('parent', models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.Spec', verbose_name='父级规格')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='product.Product', verbose_name='所属产品')),
            ],
            options={
                'verbose_name': '商品规格',
                'verbose_name_plural': '商品规格',
                'db_table': 't_specs',
                'ordering': ('-sort', '-add_time'),
            },
        ),
        migrations.CreateModel(
            name='SpecDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序优先级')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_delete', models.BooleanField(default=True, verbose_name='是否删除')),
                ('delete_time', models.DateTimeField(blank=True, default=0, null=True, verbose_name='删除时间')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('extends', models.TextField(blank=True, null=True, verbose_name='扩展数据(json格式存储)')),
                ('note', models.CharField(blank=True, max_length=160, null=True, verbose_name='规格说明')),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='毛重(g)')),
                ('length', models.IntegerField(blank=True, default=0, null=True, verbose_name='长(mm)')),
                ('height', models.IntegerField(blank=True, default=0, null=True, verbose_name='高(mm)')),
                ('width', models.IntegerField(blank=True, default=0, null=True, verbose_name='宽(mm)')),
                ('sku', models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='规格编码')),
                ('barcode', models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='条形码')),
                ('min_quantity', models.IntegerField(default=0, verbose_name='最小可购买数量')),
                ('max_quantity', models.IntegerField(default=0, verbose_name='最大可购买数量')),
                ('inventory', models.IntegerField(default=0, verbose_name='库存数量')),
                ('is_deduction_inventory', models.BooleanField(default=False, verbose_name='是否扣减库存')),
                ('spec', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='product.Spec', verbose_name='所属产品')),
            ],
            options={
                'verbose_name': '规格详情',
                'verbose_name_plural': '规格详情',
                'db_table': 't_spec_details',
                'ordering': ('-sort', '-add_time'),
            },
        ),
        migrations.CreateModel(
            name='InventoryHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序优先级')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_delete', models.BooleanField(default=True, verbose_name='是否删除')),
                ('delete_time', models.DateTimeField(blank=True, default=0, null=True, verbose_name='删除时间')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('extends', models.TextField(blank=True, null=True, verbose_name='扩展数据(json格式存储)')),
                ('change', models.IntegerField(default=0, verbose_name='变化数量')),
                ('current_inventory', models.IntegerField(default=0, verbose_name='变化后')),
                ('message', models.CharField(default='', max_length=200, verbose_name='变更原因')),
                ('note', models.TextField(default='', verbose_name='库存变更备注')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='引起库存变更的用户')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Spec', verbose_name='相关规格')),
            ],
            options={
                'verbose_name': '库存变化记录',
                'verbose_name_plural': '库存变化记录',
                'db_table': 't_inventory_histories',
                'ordering': ('-add_time',),
            },
        ),
    ]
