# Generated by Django 2.2.5 on 2019-09-12 17:50

from django.db import migrations, models
import extra_apps.DjangoUeditor.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_availablespec_interactedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='spec',
            name='is_free_shipping',
            field=models.BooleanField(default=True, verbose_name='是否包邮'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=extra_apps.DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='产品描述'),
        ),
    ]
