# Generated by Django 2.2.5 on 2019-09-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_category_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, default='logo_default.jpg', max_length=200, null=True, upload_to='static/image/brand/logo'),
        ),
    ]
