# Generated by Django 2.2.5 on 2019-09-12 18:10

from django.db import migrations, models
import extra_apps.DjangoUeditor.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20190912_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='是否热销'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='是否新品'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=extra_apps.DjangoUeditor.models.UEditorField(blank=True, default='', null=True, verbose_name='详情'),
        ),
    ]
