# Generated by Django 2.2.5 on 2019-09-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_brand_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, default='category_icon_default.jpg', max_length=200, null=True, upload_to='static/image/category/icon'),
        ),
    ]
