# Generated by Django 2.2.5 on 2019-09-13 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0006_auto_20190912_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
        migrations.AddField(
            model_name='product',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建该产品的用户'),
        ),
        migrations.AlterField(
            model_name='interactedproduct',
            name='type',
            field=models.CharField(choices=[('like', '点赞'), ('fav', '收藏'), ('watched', '看过')], max_length=20, verbose_name='行为'),
        ),
        migrations.AlterField(
            model_name='product',
            name='access_count',
            field=models.IntegerField(default=0, verbose_name='浏览次数'),
        ),
        migrations.AlterField(
            model_name='product',
            name='favorite_count',
            field=models.IntegerField(default=0, verbose_name='收藏次数'),
        ),
        migrations.AlterField(
            model_name='product',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='点赞次数'),
        ),
        migrations.CreateModel(
            name='ProductSalesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序优先级')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_delete', models.BooleanField(default=True, verbose_name='是否删除')),
                ('delete_time', models.DateTimeField(blank=True, default=0, null=True, verbose_name='删除时间')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('extends', models.TextField(blank=True, null=True, verbose_name='扩展数据(json格式存储)')),
                ('type', models.CharField(choices=[('wr', '供货和零售'), ('w', '只供货'), ('r', '只零售')], max_length=20, verbose_name='行为')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales', to='product.Product', verbose_name='相关商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales_products', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '用户商品销售模式',
                'verbose_name_plural': '用户商品销售模式',
                'db_table': 't_sales_types',
                'ordering': ('-add_time',),
            },
        ),
    ]
