# Generated by Django 2.2.5 on 2019-09-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, default='logo_default.jpg', max_length=200, null=True, upload_to='image/brand/logo'),
        ),
    ]
