# Generated by Django 2.2.5 on 2019-09-17 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20190914_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spec',
            name='parent',
        ),
        migrations.AddField(
            model_name='spec',
            name='spec_no',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='规格编码'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, default='category_icon_default.jpg', max_length=200, null=True, upload_to='image/category/icon'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.Brand', verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brief',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='商品简述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='products', to='product.Category', verbose_name='所属分类'),
        ),
        migrations.AlterField(
            model_name='product',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建用户'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=80, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='specdetail',
            name='max_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='最大可购买数量'),
        ),
        migrations.AlterField(
            model_name='specdetail',
            name='min_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='最小可购买数量'),
        ),
    ]
