# Generated by Django 2.2.5 on 2019-09-17 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20190917_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spec',
            name='is_free_shipping',
        ),
    ]
