# Generated by Django 2.2.5 on 2019-09-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_spec_is_free_shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spec',
            name='name',
        ),
        migrations.RemoveField(
            model_name='spec',
            name='value',
        ),
        migrations.AddField(
            model_name='spec',
            name='items',
            field=models.CharField(default='', max_length=200, verbose_name='规格键值对'),
        ),
    ]
