# Generated by Django 2.2.5 on 2019-09-21 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20190920_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandcategory',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='是否分类推荐'),
        ),
    ]
