# Generated by Django 2.2.5 on 2019-09-21 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_brandcategory_is_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='pid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_categories', to='product.Category', verbose_name='父级分类'),
        ),
    ]
