# Generated by Django 2.2.5 on 2019-09-12 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序优先级')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_delete', models.BooleanField(default=True, verbose_name='是否删除')),
                ('delete_time', models.DateTimeField(blank=True, default=0, null=True, verbose_name='删除时间')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('extends', models.TextField(blank=True, null=True, verbose_name='扩展数据(json格式存储)')),
                ('currency', models.CharField(choices=[('balance', '余额'), ('integral', '积分'), ('financial', '理财')], default='', max_length=20, verbose_name='电子币种')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='当前金额')),
                ('change', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='变化金额')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trans_records', to=settings.AUTH_USER_MODEL, verbose_name='交易记录所属用户')),
            ],
            options={
                'verbose_name': '交易记录',
                'verbose_name_plural': '交易记录',
                'db_table': 't_transaction_records',
                'ordering': ('-add_time',),
            },
        ),
    ]
