# Generated by Django 2.2.5 on 2019-09-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='', max_length=254, null=True, verbose_name='口令字符串'),
        ),
    ]
