# Generated by Django 2.2.5 on 2019-09-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('new', '新用户'), ('normal', '正常'), ('lp', '限制购买'), ('lw', '限制提款'), ('al', '限制全部功能'), ('frozen', '冻结')], default='0', max_length=20, verbose_name='用户状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='', max_length=254, verbose_name='口令字符串'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.CharField(choices=[('normal', '普通用户'), ('vip', '高级用户')], default='normal', max_length=20, verbose_name='用户等级'),
        ),
    ]
