# Generated by Django 2.2.5 on 2019-09-12 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序优先级')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_delete', models.BooleanField(default=True, verbose_name='是否删除')),
                ('delete_time', models.DateTimeField(blank=True, default=0, null=True, verbose_name='删除时间')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('extends', models.TextField(blank=True, null=True, verbose_name='扩展数据(json格式存储)')),
            ],
            options={
                'verbose_name': '追踪信息记录',
                'verbose_name_plural': '追踪信息记录',
                'db_table': 't_tracking_records',
                'ordering': ('-sort', '-add_time'),
            },
        ),
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序优先级')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_delete', models.BooleanField(default=True, verbose_name='是否删除')),
                ('delete_time', models.DateTimeField(blank=True, default=0, null=True, verbose_name='删除时间')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('extends', models.TextField(blank=True, null=True, verbose_name='扩展数据(json格式存储)')),
                ('id_number', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='收件人身份证号')),
                ('id_photo_front', models.ImageField(blank=True, default='', null=True, upload_to='media/image/id', verbose_name='收件人身份证正面照片')),
                ('id_photo_back', models.ImageField(blank=True, default='', null=True, upload_to='media/image/id', verbose_name='收件人身份证背面照片')),
                ('alias', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='别名')),
                ('name', models.CharField(default='', max_length=60, verbose_name='收件人姓名')),
                ('telephone', models.CharField(default='', max_length=20, verbose_name='收件人联系电话')),
                ('country', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='收件人地址-国家')),
                ('province', models.PositiveIntegerField(default=1, verbose_name='收件人地址-省')),
                ('city', models.PositiveIntegerField(default=1, verbose_name='收件人地址-市')),
                ('district', models.PositiveIntegerField(default=1, verbose_name='收件人地址-区县')),
                ('street', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='收件人地址-街道 乡村')),
                ('detail', models.CharField(default='', max_length=254, verbose_name='收件人地址-具体地址')),
                ('postcode', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='邮编')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否为默认收件人地址')),
                ('is_sender', models.BooleanField(default=False, verbose_name='是否为发件人地址')),
                ('last_use_time', models.DateTimeField(blank=True, null=True, verbose_name='用户最后使用这个邮寄信息的时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_info_book', to=settings.AUTH_USER_MODEL, verbose_name='创建该邮寄信息的用户')),
            ],
            options={
                'verbose_name': '地址信息',
                'verbose_name_plural': '地址信息',
                'db_table': 't_shipping_infos',
                'ordering': ('-sort', '-add_time'),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序优先级')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_delete', models.BooleanField(default=True, verbose_name='是否删除')),
                ('delete_time', models.DateTimeField(blank=True, default=0, null=True, verbose_name='删除时间')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('extends', models.TextField(blank=True, null=True, verbose_name='扩展数据(json格式存储)')),
                ('name', models.CharField(default='', max_length=255, verbose_name='地区名称')),
                ('level', models.PositiveIntegerField(verbose_name='级别类型 1:国家, 2:省, 3:市, 4:区县, 5:街道, 9:其他')),
                ('spell', models.CharField(default='', max_length=60, verbose_name='拼写')),
                ('parent', models.ForeignKey(db_column='parent_id', on_delete=django.db.models.deletion.CASCADE, related_name='jurisdictions', to='logistics.Region', verbose_name='父级地区')),
            ],
            options={
                'verbose_name': '地区',
                'verbose_name_plural': '地区',
                'db_table': 't_regions',
                'ordering': ('-sort', '-add_time'),
            },
        ),
    ]
