# Generated by Django 2.2.5 on 2019-09-14 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinginfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_info_book', to=settings.AUTH_USER_MODEL, verbose_name='创建该邮寄信息的用户'),
        ),
        migrations.AddField(
            model_name='region',
            name='parent',
            field=models.ForeignKey(db_column='parent_id', on_delete=django.db.models.deletion.CASCADE, related_name='jurisdictions', to='logistics.Region', verbose_name='父级地区'),
        ),
        migrations.AddField(
            model_name='expressfeerecord',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='logistics.ExpressFeeGroup', verbose_name='所属快递费分组'),
        ),
        migrations.AddField(
            model_name='expressfeerecord',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logistics.Region', verbose_name='地区'),
        ),
    ]
