# Generated by Django 2.2.5 on 2019-09-14 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_auto_20190914_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jurisdictions', to='logistics.Region', verbose_name='父级地区'),
        ),
    ]
