# Generated by Django 2.2.5 on 2019-09-12 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_region_shippinginfo_trackingrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressfeegroup',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='分组名称'),
        ),
        migrations.AddField(
            model_name='expressfeerecord',
            name='currency',
            field=models.CharField(blank=True, default='CNY', max_length=3, null=True, verbose_name='计价币种'),
        ),
        migrations.AddField(
            model_name='expressfeerecord',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='logistics.ExpressFeeGroup', verbose_name='所属快递费分组'),
        ),
        migrations.AddField(
            model_name='expressfeerecord',
            name='price_continue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='续重价格'),
        ),
        migrations.AddField(
            model_name='expressfeerecord',
            name='price_first',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='首重价格'),
        ),
        migrations.AddField(
            model_name='expressfeerecord',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logistics.Region', verbose_name='地区'),
        ),
        migrations.AddField(
            model_name='expressfeerecord',
            name='weight_continue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='续重克数'),
        ),
        migrations.AddField(
            model_name='expressfeerecord',
            name='weight_first',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='首重克数'),
        ),
        migrations.AddField(
            model_name='trackingnumber',
            name='LogisticsCompany',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tracking_numbers', to='logistics.LogisticsCompany', verbose_name='所属快递'),
        ),
        migrations.AddField(
            model_name='trackingnumber',
            name='number',
            field=models.CharField(default='', max_length=20, verbose_name='单号'),
        ),
        migrations.AddField(
            model_name='trackingnumber',
            name='obj_id',
            field=models.IntegerField(default=1, verbose_name='所属对象id'),
        ),
        migrations.AddField(
            model_name='trackingrecord',
            name='message',
            field=models.CharField(default='', max_length=100, verbose_name='记录内容'),
        ),
        migrations.AddField(
            model_name='trackingrecord',
            name='tracking_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_records', to='logistics.TrackingNumber', verbose_name='快递单号'),
        ),
    ]
