# Generated by Django 2.2.5 on 2019-09-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_auto_20190914_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expressfeegroup',
            name='delete_time',
        ),
        migrations.RemoveField(
            model_name='expressfeerecord',
            name='delete_time',
        ),
        migrations.RemoveField(
            model_name='logisticscompany',
            name='delete_time',
        ),
        migrations.RemoveField(
            model_name='region',
            name='delete_time',
        ),
        migrations.RemoveField(
            model_name='shippinginfo',
            name='delete_time',
        ),
        migrations.RemoveField(
            model_name='trackingnumber',
            name='delete_time',
        ),
        migrations.RemoveField(
            model_name='trackingrecord',
            name='delete_time',
        ),
        migrations.AlterField(
            model_name='expressfeegroup',
            name='extends',
            field=models.TextField(blank=True, default='', null=True, verbose_name='扩展数据(json格式存储)'),
        ),
        migrations.AlterField(
            model_name='expressfeegroup',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='expressfeerecord',
            name='extends',
            field=models.TextField(blank=True, default='', null=True, verbose_name='扩展数据(json格式存储)'),
        ),
        migrations.AlterField(
            model_name='expressfeerecord',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='logisticscompany',
            name='extends',
            field=models.TextField(blank=True, default='', null=True, verbose_name='扩展数据(json格式存储)'),
        ),
        migrations.AlterField(
            model_name='logisticscompany',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='region',
            name='extends',
            field=models.TextField(blank=True, default='', null=True, verbose_name='扩展数据(json格式存储)'),
        ),
        migrations.AlterField(
            model_name='region',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='extends',
            field=models.TextField(blank=True, default='', null=True, verbose_name='扩展数据(json格式存储)'),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='trackingnumber',
            name='extends',
            field=models.TextField(blank=True, default='', null=True, verbose_name='扩展数据(json格式存储)'),
        ),
        migrations.AlterField(
            model_name='trackingnumber',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='trackingrecord',
            name='extends',
            field=models.TextField(blank=True, default='', null=True, verbose_name='扩展数据(json格式存储)'),
        ),
        migrations.AlterField(
            model_name='trackingrecord',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
