# Generated by Django 2.2.5 on 2019-09-12 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_agent_agentgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序优先级')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_delete', models.BooleanField(default=True, verbose_name='是否删除')),
                ('delete_time', models.DateTimeField(blank=True, default=0, null=True, verbose_name='删除时间')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('extends', models.TextField(blank=True, null=True, verbose_name='扩展数据(json格式存储)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='建议零售价')),
                ('agent_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.AgentGroup', verbose_name='所属代理分组')),
            ],
            options={
                'verbose_name': '优惠',
                'verbose_name_plural': '优惠',
                'db_table': 't_promotions',
                'ordering': ('-sort', '-add_time'),
            },
        ),
    ]
