# Generated by Django 2.2.5 on 2019-09-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_promotion_agent_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='delete_time',
        ),
        migrations.AlterField(
            model_name='promotion',
            name='extends',
            field=models.TextField(blank=True, default='', null=True, verbose_name='扩展数据(json格式存储)'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
