# Generated by Django 2.2.5 on 2019-09-14 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0002_auto_20190914_1357'),
        ('payment', '0001_initial'),
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatushistory',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='引起订单状态变更的用户'),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='histories', to='order.Order', verbose_name='相关订单'),
        ),
        migrations.AddField(
            model_name='orderrecord',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.Order', verbose_name='所属订单'),
        ),
        migrations.AddField(
            model_name='orderrecord',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='product.Product', verbose_name='所购商品'),
        ),
        migrations.AddField(
            model_name='orderrecord',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Spec', verbose_name='所购型号'),
        ),
        migrations.AddField(
            model_name='order',
            name='consignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='be_consignee_orders', to='logistics.ShippingInfo', verbose_name='收件人信息'),
        ),
        migrations.AddField(
            model_name='order',
            name='consignor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='be_consignor_orders', to='logistics.ShippingInfo', verbose_name='发件人信息'),
        ),
        migrations.AddField(
            model_name='order',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='order',
            name='express',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='logistics.LogisticsCompany', verbose_name='快递公司'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payment.PaymentMethod', verbose_name='支付方式'),
        ),
        migrations.AddField(
            model_name='aftersalesstatushistory',
            name='after_sales_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='histories', to='order.AfterSalesRecord', verbose_name='相关售后'),
        ),
        migrations.AddField(
            model_name='aftersalesstatushistory',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='引起订单状态变更的用户'),
        ),
        migrations.AddField(
            model_name='aftersalesrecord',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='after_sales_demands', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='aftersalesrecord',
            name='express',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='logistics.LogisticsCompany', verbose_name='快递公司'),
        ),
        migrations.AddField(
            model_name='aftersalesrecord',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='after_sales_records', to='order.Order', verbose_name='相关订单'),
        ),
        migrations.AddField(
            model_name='aftersalesrecord',
            name='order_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.OrderRecord', verbose_name='相关订单记录'),
        ),
        migrations.AddField(
            model_name='aftersalesrecord',
            name='shipping_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='logistics.ShippingInfo', verbose_name='退货地址'),
        ),
    ]
