# Generated by Django 2.2.5 on 2019-09-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='trade_no',
            field=models.CharField(default='', max_length=30, unique=True, verbose_name='交易流水号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.CharField(default='', max_length=30, unique=True, verbose_name='订单号'),
        ),
    ]
