# Generated by Django 2.2.5 on 2019-09-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序优先级')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_delete', models.BooleanField(default=True, verbose_name='是否删除')),
                ('delete_time', models.DateTimeField(blank=True, default=0, null=True, verbose_name='删除时间')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('extends', models.TextField(blank=True, null=True, verbose_name='扩展数据(json格式存储)')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('brief', models.CharField(blank=True, max_length=255, null=True, verbose_name='简述')),
                ('filename', models.CharField(max_length=200, verbose_name='文件名')),
                ('type', models.CharField(choices=[('image', '图片'), ('video', '视频'), ('text', '文本')], max_length=10, verbose_name='媒体类型')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/image/article', verbose_name='图片')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/video/article', verbose_name='视频')),
            ],
            options={
                'verbose_name': '文章媒体',
                'verbose_name_plural': '文章媒体',
                'db_table': 't_articles_medias',
                'ordering': ('-sort', '-add_time'),
            },
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序优先级')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_delete', models.BooleanField(default=True, verbose_name='是否删除')),
                ('delete_time', models.DateTimeField(blank=True, default=0, null=True, verbose_name='删除时间')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('extends', models.TextField(blank=True, null=True, verbose_name='扩展数据(json格式存储)')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('brief', models.CharField(blank=True, max_length=255, null=True, verbose_name='简述')),
                ('filename', models.CharField(max_length=200, verbose_name='文件名')),
                ('type', models.CharField(choices=[('image', '图片'), ('video', '视频'), ('text', '文本')], max_length=10, verbose_name='媒体类型')),
                ('position', models.CharField(choices=[('cover', '封面'), ('slider', '轮播图'), ('detail', '详情')], max_length=10, verbose_name='媒体位置')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/image/product', verbose_name='图片')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/video/product', verbose_name='视频')),
            ],
            options={
                'verbose_name': '商品媒体',
                'verbose_name_plural': '商品媒体',
                'db_table': 't_product_medias',
                'ordering': ('-sort', '-add_time'),
            },
        ),
        migrations.CreateModel(
            name='SystemMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序优先级')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_delete', models.BooleanField(default=True, verbose_name='是否删除')),
                ('delete_time', models.DateTimeField(blank=True, default=0, null=True, verbose_name='删除时间')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('extends', models.TextField(blank=True, null=True, verbose_name='扩展数据(json格式存储)')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('brief', models.CharField(blank=True, max_length=255, null=True, verbose_name='简述')),
                ('filename', models.CharField(max_length=200, verbose_name='文件名')),
                ('type', models.CharField(choices=[('image', '图片'), ('video', '视频'), ('text', '文本')], max_length=10, verbose_name='媒体类型')),
                ('position', models.CharField(choices=[('logo', '标志'), ('slider', '幻灯片')], max_length=10, verbose_name='媒体位置')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/image/system', verbose_name='图片')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/video/system', verbose_name='视频')),
                ('link', models.CharField(default='', max_length=200, verbose_name='链接')),
            ],
            options={
                'verbose_name': '系统媒体',
                'verbose_name_plural': '系统媒体',
                'db_table': 't_system_medias',
                'ordering': ('-sort', '-add_time'),
            },
        ),
    ]
