# Generated by Django 2.2.5 on 2019-09-14 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('community', '0001_initial'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmedia',
            name='belong_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='medias', to='product.Spec', verbose_name='所属规格'),
        ),
        migrations.AddField(
            model_name='articlesmedia',
            name='belong_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='medias', to='community.Articles', verbose_name='所属规格'),
        ),
    ]
