# Generated by Django 2.2.5 on 2019-09-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlesmedia',
            name='content',
        ),
        migrations.RemoveField(
            model_name='productmedia',
            name='content',
        ),
        migrations.RemoveField(
            model_name='systemmedia',
            name='content',
        ),
        migrations.AlterField(
            model_name='articlesmedia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/image/article', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='articlesmedia',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/video/article', verbose_name='视频'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/image/product', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/video/product', verbose_name='视频'),
        ),
        migrations.AlterField(
            model_name='systemmedia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/image/system', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='systemmedia',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/video/system', verbose_name='视频'),
        ),
    ]
