# Generated by Django 2.2.5 on 2019-09-12 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ('-sort', '-add_time'), 'verbose_name': '支付方式', 'verbose_name_plural': '支付方式'},
        ),
    ]
