# Generated by Django 2.2.5 on 2019-09-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序优先级')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_delete', models.BooleanField(default=True, verbose_name='是否删除')),
                ('delete_time', models.DateTimeField(blank=True, default=0, null=True, verbose_name='删除时间')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('extends', models.TextField(blank=True, null=True, verbose_name='扩展数据(json格式存储)')),
                ('belong_to', models.PositiveIntegerField(verbose_name='归属对象')),
                ('owner_type', models.CharField(max_length=20, verbose_name='归属对象类型')),
                ('use_for', models.CharField(max_length=20, verbose_name='用途')),
                ('filename', models.CharField(max_length=200, verbose_name='文件名')),
                ('type', models.CharField(choices=[('image', '图片'), ('video', '视频'), ('text', '文本')], max_length=10, verbose_name='媒体类型')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/image/', verbose_name='图片')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/video/', verbose_name='视频')),
                ('content', models.TextField(blank=True, null=True, verbose_name='文本')),
            ],
            options={
                'verbose_name': '媒体',
                'verbose_name_plural': '媒体',
                'db_table': 't_medias',
                'ordering': ('-sort', '-add_time'),
            },
        ),
    ]
