# Generated by Django 2.2.5 on 2019-09-14 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagerecipient',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inbox', to=settings.AUTH_USER_MODEL, verbose_name='收信人'),
        ),
        migrations.AddField(
            model_name='message',
            name='announcer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='outbox', to=settings.AUTH_USER_MODEL, verbose_name='发布人'),
        ),
        migrations.AddField(
            model_name='interactedarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='users', to='community.Articles', verbose_name='相关文章'),
        ),
        migrations.AddField(
            model_name='interactedarticle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='interacted_articles', to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='articles',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='创建用户'),
        ),
    ]
