# Generated by Django 2.2.5 on 2019-09-12 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_interactedarticle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media',
        ),
    ]
