# Generated by Django 2.2.5 on 2019-09-13 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0004_delete_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.AddField(
            model_name='articles',
            name='access_count',
            field=models.IntegerField(default=0, verbose_name='浏览次数'),
        ),
        migrations.AddField(
            model_name='articles',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='创建用户'),
        ),
        migrations.AddField(
            model_name='articles',
            name='favorite_count',
            field=models.IntegerField(default=0, verbose_name='收藏次数'),
        ),
        migrations.AddField(
            model_name='articles',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='点赞次数'),
        ),
        migrations.AlterField(
            model_name='interactedarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='users', to='community.Articles', verbose_name='相关文章'),
        ),
        migrations.CreateModel(
            name='MessageRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序优先级')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_delete', models.BooleanField(default=True, verbose_name='是否删除')),
                ('delete_time', models.DateTimeField(blank=True, default=0, null=True, verbose_name='删除时间')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('extends', models.TextField(blank=True, null=True, verbose_name='扩展数据(json格式存储)')),
                ('is_topping', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('is_watched', models.BooleanField(default=False, verbose_name='是否已读')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipients', to='community.Message', verbose_name='消息')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inbox', to=settings.AUTH_USER_MODEL, verbose_name='收信人')),
            ],
            options={
                'verbose_name': '消息接受人',
                'verbose_name_plural': '消息接受人',
                'db_table': 't_message_recipients',
                'ordering': ('-sort', '-add_time'),
            },
        ),
    ]
